blueprint:
  name: Diaper Tracker – Empty Bag Reset
  description: Save previous start, reset bag utility meter, set new start, and optionally trigger the pause helpers. (No TTS.)
  domain: automation
  input:
    reset_button:
      name: Trigger entity (button or proxy)
      selector: { entity: { domain: input_button } }
    bag_meter:
      name: Bag utility meter sensor
      selector: { entity: { domain: sensor } }
    started_now:
      name: Input datetime – bag started (current)
      selector: { entity: { domain: input_datetime } }
    started_prev:
      name: Input datetime – bag started (previous)
      selector: { entity: { domain: input_datetime } }
    pause_flag:
      name: (Optional) Pause helper boolean
      selector: { entity: { domain: input_boolean } }
      default: ""
    pause_timer:
      name: (Optional) Pause timer
      selector: { entity: { domain: timer } }
      default: ""

mode: single
trigger:
  - platform: state
    entity_id: !input reset_button
action:
  - variables:
      prev_start: "{{ states('!input started_now') }}"
      pause_flag: !input pause_flag
      pause_timer: !input pause_timer
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ pause_flag not in [none, ''] }}"
        sequence:
          - service: input_boolean.turn_on
            data:
              entity_id: "{{ pause_flag }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ pause_timer not in [none, ''] }}"
        sequence:
          - service: timer.start
            data:
              entity_id: "{{ pause_timer }}"
  - service: input_datetime.set_datetime
    target: { entity_id: !input started_prev }
    data:
      datetime: >
        {% if prev_start not in ['unknown','unavailable',''] %}
          {{ prev_start }}
        {% else %}
          {{ now().timestamp() | timestamp_local }}
        {% endif %}
  - service: utility_meter.reset
    target: { entity_id: !input bag_meter }
  - service: input_datetime.set_datetime
    target: { entity_id: !input started_now }
    data: { datetime: "{{ now().timestamp() | timestamp_local }}" }
